Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WbAppMVC.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth


        [HttpPost]
        public ActionResult Login()
        {
            var Data = "You Are Logged In Succsessfully";
            return Json(Data);
        }

        [HttpGet]
        public ActionResult GtoToLogin()
        {
            return View("Login");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WbAppMVC.Classes;
using WbAppMVC.Models;
using WbAppMVC.Models.MyModels;
using WbAppMVC.ViewModels;

namespace WbAppMVC.Controllers
{
    class HallSearch
    {
        public int HallID { get; set; }
        public string HallCode { get; set; }
        public string BranchName { get; set; }

    }
    public class HomeController : Controller
    {
        private smartEntities db = new smartEntities();
        public ActionResult Index()
        {

            var Users = db.Users.ToList();
            var students = db.students.ToList();
            return View(students);
        }

        public ActionResult Detail(string Id)
        {
            //    ViewBag.Message = "Your application description page.";

            var st = db.students.Where(x => x.Id == Id).FirstOrDefault();
            return View(st);
        }

        public ActionResult Delete()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Create()
        {


            var student = new student { };
            return View(student);
        }

        [HttpPost]
        public ActionResult CreateStudent(student student)
        {



            var ID = Guid.NewGuid();
            student.Id = ID.ToString();
            db.students.Add(student);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }



        public ActionResult Parents(string id)
        {

            var parents = db.students.Where(x => x.Id == id).Select(x => x.parents).ToList().FirstOrDefault();
            //   ViewData["parents"] = parents;

            return View("Parents/index", parents);
        }


        public ActionResult CreateParent()
        {
            var student = db.students.ToList();
            ViewData["Students"] = student;
            return View("Parents/Create");
        }



        [HttpPost]
        public ActionResult CreateParent(parent parent)
        {
            var ID = Guid.NewGuid();
            parent.Id = ID.ToString();
            var studentId = Request.Form.GetValues("ChildId")[0];

            var student = db.students.Where(x => x.Id == studentId).FirstOrDefault();
            if (student.secondname != parent.firstname)
            {
                student.secondname = parent.firstname;
            }
            if (student.thirdname != parent.secondname)
            {
                student.thirdname = parent.secondname;
            }
            student.parents.Add(parent);
            db.students.AddOrUpdate(student);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }



        public ActionResult CreateSubject()
        {


            return View("Subject/Create");
        }


        public ActionResult SubjectIndex(string id)
        {
            var AllSubjects = db.subjects.ToList();

            var Registerdsubject = db.subjects.Where(x=>x.studentId == id).Select(x=>x.subjectname).ToList();



            List<string> SubjRemain = new List<string>();
            foreach (var subj in AllSubjects) {

                if (!Registerdsubject.Contains(subj.subjectname)) {

                    SubjRemain.Add(subj.subjectname);
                }
            
            };

            ViewData["Subjects"] = SubjRemain.Distinct().ToList();
            ViewData["StudentId"] = id;
           return View("Subject/Index", Registerdsubject);
        }


        public ActionResult StudentSubject(string subjName,string StudentId)
        {
            var ID = Guid.NewGuid();
          
          
            db.students.FirstOrDefault(x => x.Id == StudentId).subjects.Add(new subject { subjectname = subjName ,Id = ID.ToString()});
            db.SaveChanges();



            return RedirectToAction("Index","Home");
        }
    }
}

Controllers/StudentController.cs
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;

using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Cryptography.Xml;
using System.Text;
using System.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI.WebControls;
using WbAppMVC.Models;
using System.Drawing;
using Image = System.Drawing.Image;
using System.Drawing.Imaging;
using Microsoft.SqlServer.Server;
using static System.Net.WebRequestMethods;
using GSF.IO;
using WbAppMVC.Models.MyModels;

namespace WbAppMVC.Controllers
{
    public class StudentController : Controller
    {



        private smartEntities db = new smartEntities();

        [HttpPost]
        public ActionResult DataQuery(){
            db.Configuration.ProxyCreationEnabled = false;
            var Currentdate = DateTime.Now.ToString("yyyy/MM/dd").Replace('/','-');
           
            var Date = Request.Form.GetValues("date")[0];
            var Order = Request.Form.GetValues("order")[0];
            var filterBy = Request.Form.GetValues("filterBy")[0];
            var UserId = Request.Form.GetValues("UserId")[0];
            var Signiture = Request.Form.GetValues("canvas")[0].Split(',')[1];
            if (Signiture != "" && UserId!="") {
              
                var img =   Convert.FromBase64String(Signiture);
                String path = System .Web.HttpContext.Current.Server.MapPath("~/Content/Image/"+UserId+".png");
                string imgPath = Path.Combine(path, "New");

                System.IO.File.WriteAllBytes(path, img);
    
            }
            double days = 19000;
            if (Date != "")
            {
               
                days = (Convert.ToDateTime(Currentdate) - Convert.ToDateTime(Date)).TotalDays;
            }
            days /= 365;    
            var years = (int)days;

            List<student> students;

            Expression<Func<student,string>> myExpression = (St) => St.firstname;
            if (filterBy == "SecondName")
            {
                myExpression = (St) => St.secondname;
            }
            else if (filterBy == "ThirdName")
            {
                myExpression = (St) => St.thirdname;
            }
            else if (filterBy == "Age")
            {
                myExpression = (St) => St.age.ToString();
            }
            else if(filterBy == "Email"){
                myExpression = (St) => St.email;
            }
            else if (filterBy == "Wallet")
            {
                myExpression = (St) => St.wallet.ToString();
            }






            if (Order == "Dec")
            {
                 students = db.students.Where(x => x.age <= years).OrderByDescending(myExpression).ToList();
            }
            else {

                 students = db.students.Where(x => x.age <= years).OrderBy(myExpression).ToList();
            }
          

            var Data = Json(students);
            //JsonResult categoryJson = new JsonResult();
            //categoryJson.Data = students;
            return Json(students);
        }



   


        public ActionResult DeleteStudent(string id) {

          var student =  db.students.FirstOrDefault(x => x.Id == id);
            if (student == null)
                return RedirectToAction("Index", "Home");
            db.students.Remove(student);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        public static Image Base64ToImage(string base64String)
        {

            byte[] imageBytes = Convert.FromBase64String(base64String);
            Image image;
            using (MemoryStream inStream = new MemoryStream())
            {
                inStream.Write(imageBytes, 0, imageBytes.Length);

                image = Bitmap.FromStream(inStream);
                // image.Save(inStream, System.Drawing.Imaging.ImageFormat.Png);
               // image.Save(System.Web.HttpServerUtility Server.MapPath("~/Uploads/"+fileName),
                image.Save(inStream, ImageFormat.Png);
            }

            return image;
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Detail.cshtml
@model WbAppMVC.Models.student


<h2>Details</h2>

@{
    var i = 0;
 }

 <link rel="stylesheet"  type="text/css" href="~/Content/Css/StudentDetails.css" />

<div class="container">
    <div class="card_container">
        <div class="header">
            <h2></h2>
        </div>
        <div class="details">
            <div class="img_container">
                 <img src="https://www.kindpng.com/picc/m/173-1731325_person-icon-png-transparent-png.png"/>
            </div>
            <div class="item"><h4>firstname :</h4>  <span>@Model.firstname</span></div>
            <div class="item"><h4>secondname :</h4> <span> @Model.secondname </span></div>
            <div class="item"><h4>thirdname :</h4> <span>  @Model.thirdname</span></div>
            <div class="item"><h4>email :</h4> <span>  @Model.email</span></div>
            @foreach (var item in Model.subjects)
            {
                
                i++;
                 
                <div class="item">subj @i : @item.subjectname</div>
            }


            <div class="parents container">
<div>
             @{
                i=0;
             }
                @if(Model.parents.Count > 0){
                 <div> Parents</div>
                foreach (var item in Model.parents)
            {
                
                i++;
                 
                <div class="item"> @i : @item.firstname</div>
            }
             }
            </div>
          </div>     

            <a  href="@Url.Action("DeleteStudent","Student", new { id = Model.Id})" class="btn btn-danger">Delete</a>
        </div>

    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<WbAppMVC.Models.student>

<br />
<br />

<link rel="stylesheet" type="text/css" href="~/Content/Css/canvas.css" />
<link rel="stylesheet" type="text/css" href="~/Content/Css/StudentIndex.css" />

<a  href="@Url.Action("GtoToLogin", "Auth")" >Login</a>

<!-- BEGIN PAGE CONTENT-->
<div id="signature"></div>
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>الــقــاعــات
                </div>
                <div class="tools">
                </div>
            </div>

            @*filters*@
            @*<div class="filter">
                <div class="id">
                    <label>Date</label>
                    <input class="filter_selector" onchange="javascript:DataSearch()" type="date" id="Date" />

                </div>

                <div class="id">
                    <label>Orders</label>
                    <select onchange="javascript:DataSearch()" class="filter_selector" id="order">
                        <option value="Asc">Asc</option>
                        <option value="Dec">Dec</option>
                    </select>

                </div>


                <div class="id">
                    <label>FilterBy</label>
                    <select onchange="javascript:DataSearch()" class="filter_selector" id="filterBy">
                        <option value="FirstName">FirstName</option>
                        <option value="SecondName">SecondName</option>
                        <option value="ThirdName">ThirdName</option>
                        <option value="Age">Age</option>
                        <option value="Email">Email</option>
                        <option value="Wallet">Wallet</option>
                    </select>

                </div>*@



            </div>
            @*<input onkeyup="javascript:DataSearch()" id="searchBar" />*@
            <div class="portlet-body">


                <table class="mytable table table-striped table-bordered dt-responsive"  id="mytable">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Email</th>
                            <th>firstname</th>
                            <th>SecondName</th>
                            <th>ThirdName</th>
                            <th>Wallet</th>
                            <th>Age</th>
                            <th>Opearations</th>
                        </tr>
                    </thead>

                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>emai</th>
                            <th>firstname</th>
                            <th>SecondName</th>
                            <th>ThirdName</th>
                            <th>Wallet</th>
                            <th>age</th>
                            <th>age</th>
                            <th>Opearations</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="canvas_wrapper" id="sketch">
                <canvas id="paint"></canvas>

                <img class="canvasimg" id="canvasimg" src="" />
            </div>
            <button class="btn btn-primary" onclick="javascript:SaveCanvas()">Save</button>
            <button class="btn btn-danger" onclick="javascript:Clear()">Clear</button>
        </div>
    </div>


<script type="text/javascript" src="~/Scripts/canavas.js"></script>
<script>

    // Ajax dataTabele

    $(document).ready(function () {
        console.log("Ready");
        $('#mytable').dataTable({
            "processing": true,
            "serverSide": true,
            "filter": true,
            "responsive": true,
            "scrollCollapse": true,
            "paging": true,
            "searching": true,
            "ordering": true,

            "ajax": {
                "url": "/StudentQuery/NewDataQuery",
                "type": "POST",
                "datatype": "json"
            },
            "dom": 'Bfrtip',
            // Buttons
            "buttons": [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
            "columnDefs": [{
                "targets": [0],
                "visible": true,
                "searchable": false
            }],
            "columns": [
                { "data": "Id", "name": "firstname", "autowidth": true },
                { "data": "email", "name": "secondname", "autowidth": true },
                { "data": "firstname", "name": "secondname", "autowidth": true },
                { "data": "secondname", "name": "secondname", "autowidth": true },
                { "data": "thirdname", "name": "secondname", "autowidth": true },
                { "data": "wallet", "name": "secondname", "autowidth": true },
                { "data": "age", "name": "secondname", "autowidth": true },
                {
                    "render": function (data, type, row, meta) {
                        return   `
                                    <a class="btn btn-primary"
                                       href="@Url.Action("Detail","Home")/${row.Id}">Details</a>
                                    <a class="btn btn-success"
                                       href="@Url.Action("Create", "Home")/${row.Id}">Create</a>
                      `
                    }
                }



            ]
        })
    })
</script>

Views/Home/create.cshtml
@model WbAppMVC.Models.student

<h2>Add New Student</h2>


<link rel="stylesheet" type="text/css" href="~/Content/Css/create.css" />



<div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input id="email" type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="Email" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>
<div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="passowrd" placeholder="Password">
</div>



<div class="form-group">
    <label class="form-check-label" >firstname</label>
    <input class="form-control" type="text" id="firstname" placeholder="firstname">

</div>

<div class="form-group">
    <label class="form-check-label" for="exampleCheck1">secondname</label>
    <input class="form-control" type="text" id="secondname" placeholder="secondname">

</div>

<div class="form-group">
    <label class="form-check-label" for="exampleCheck1">thirdname</label>
    <input class="form-control" type="text" id="thirdname" placeholder="thirdname">

</div>





<div class="form-group">
    <label class="form-check-label" for="exampleInputEmail1">Gender</label>
    <select class="gender" id="gender">
        <option class="gender" value="male">Male</option>
        <option class="gender" value="female">female</option>
    </select>

</div>



<div class="form-group">
    <label class="form-check-label">age</label>
    <input class="form-control" type="number" id="age" placeholder="Default input">

</div>

<div class="form-group">
    <label class="form-check-label" for="exampleCheck1">Wallet</label>
    <input id="wallet" class="form-control" type="text" placeholder="Wallet">

</div>
<button onclick="javascript:clicked()" class="btn btn-success">Create</button>
@*<a href="@Url.Action("CreateStudent","Home",new WbAppMVC.Models.MyModels.StudentID{ email=Model.email,password=Model.password })" class="btn btn-success">Create</a>*@



<script>

    $(document).ready(function () {


        console.log("xxxx")
    })
    function clicked() {
        console.log("Button Clicked")
        var Email = $('#email').val()
        var Passowrd = $('#password').val()
        var Wallet = $('#wallet').val()
        var age = $('#age').val()
        var Gender = $('#gender').val()
        var firstname = $('#firstname').val()
        var secondname = $('#secondname').val()
        var thirdname = $('#thirdname').val()


        Student = {

        }
        Student['passowrd'] = Passowrd
        Student['email'] = Email
        Student['wallet'] = Wallet
        Student['age'] = age
        Student['id'] = "xxxx"
        Student['gender'] = Gender
        Student['firstname'] = firstname
        Student['secondname'] = secondname
        Student['thirdname'] = thirdname




        $.ajax({
            url: 'https://localhost:44357/Home/CreateStudent',
            data: Student,
            type: "post",

            success: function (savingStatus) {
                console.log("Succsess Ajax")
                $("#hdnOrigComments").val($('#txtComments').val());
                $('#lblCommentsNotification').text(savingStatus);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log("Error Ajax")
                $('#lblCommentsNotification').text("Error encountered while saving the comments.");
            }
        });

    }


</script>